require 'rails_duplicate_key_checker'
require 'rails_duplicate_key_checker/checker'
require 'rails_duplicate_key_checker/migration_generator'
require 'rails_duplicate_key_checker/duplicate_keys_analyzer'

module RailsDuplicateKeyChecker
end
